name: "abhinesh"
spring:
  cloud:
    config:
      uri: http://202.149.218.74:10088
      fail-fast: true
    stream:
      bindings:
        SinkChannel:
          destination: rabbitpubSubExchange
          binder: local_rabbit
          group: rabbitMQGroup
        SourceChannel:
          destination: rabbitpubSubExchange
          binder: local_rabbit
      binders:
         local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.1.248
                port: 5672
                username: kg
                password: kg
                virtual-host: /
  zipkin:
    base-url: http://192.168.1.170:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1

##Redis 
redis:
  host: 202.149.218.74
  port: 6379
  time-to-live: 120

feign:
   hystrix:
     enabled: true
   client:
      config:
        default:
          connectTimeout: 900000
          readTimeout: 900000
          loggerLevel: FULL
   #compression:
         #mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,,application/xml,image/jpeg
         #min-request-size: 2048
         #request:
           #enabled: true 
         #response:
           #enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.config: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    com.epps.eatigo: DEBUG
 
