
name: "abhinesh"
spring:
  cloud:
    config:
      uri: http://202.149.218.74:10088
      fail-fast: true
    stream:
      bindings:
        SinkChannel:
          destination: rabbitpubSubExchange
          binder: local_rabbit
          group: rabbitMQGroup
        SourceChannel:
          destination: rabbitpubSubExchange
          binder: local_rabbit
      binders:
         local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 202.149.218.74
                port: 5672
                username: kg
                password: kg
                virtual-host: /
##Redis 
redis:
  host: 202.149.218.74
  port: 6379
  time-to-live: 120

feign:
   client:
      config:
        default:
          connectTimeout: 900000
          readTimeout: 900000
          loggerLevel: FULL
