spring:
   application:
    name: eatigoNotification 

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,,application/xml,image/jpeg
    min-response-size: 2048
  http2:
    enabled: true
  servlet:
    context-path: /eatigoNotification
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

    
logging:
  level:
    root: INFO
    org.springframework.cloud.config: ERROR
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG

# Check - Multiple Zone Eureka Zone
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8093/eureka}
  instance:
    preferIpAddress: true

feign:
   hystrix:
     enabled: true
   client:
      config:
        default:
          connectTimeout: 900000
          readTimeout: 900000
          loggerLevel: basic
   compression:
         mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,,application/xml,image/jpeg
         min-request-size: 2048
         request:
           enabled: true 
         response:
           enabled: true

#Database Configuration
jdbc-url: jdbc:postgresql://202.149.218.74:5436/eatigo
jdbc-driverClassName: org.postgresql.Driver
jdbc-username: epps_programmer
jdbc-password: atul@1978eppsprogrammer

##maximum number of milliseconds that a client will wait for a connection
connection-timeout: 10000
##minimum number of idle connections maintained by HikariCP in a connection pool
minimum-idle: 2
##maximum pool size
maximum-pool-size: 10
##maximum idle time for connection
idle-timeout: 10000





    
#defaullt value is 90 seconds
#lease-expiration-duration-in-seconds:60.

#default value is 60 seconds 
#lease-renewal-interval-in-seconds: 20  

#default eviction time : 60
# For Multiple Zone
  #z1: http://localhost:5001/eureka
  #z1: http://localhost:5001/eureka
  #z1: http://localhost:5001/eureka
