server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,,application/xml,image/jpeg
    min-response-size: 2048
  http2:
    enabled: true
  servlet:
    context-path: /eatigoWeb
  port: 10081

spring:
  application:
    name: eatigoWeb
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  #resources:
    #cache:
      #cachecontrol:
        #cache-private: true
        #cache-public: true
        #max-age: 120
        #must-revalidate: true
  servlet:
    multipart:
      file-size-threshold: 2KB
      location: /tmp
      max-file-size: 50MB
      max-request-size: 75MB
  
  zipkin:
    base-url: http://202.149.218.74:9411
  sleuth:
    sampler:
      percentage: 1.0
      
logging:
  file:
    name: ${spring.application.name}
  level:
    root: INFO
    com.epps.eatigo.module.infrastructure.feignclient.EatigoCoreFeignClient: DEBUG  
eureka:
  instance:
     hostname: 202.149.218.74
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10089/eureka/

feign:
   compression:
      request:
        enable: true
        mime-types: text/xml,application/xml,application/json
        min-request-size: 2048
   client:
      config:
        default:
          connectTimeout: 60000
          readTimeout: 60000
          loggerLevel: FULL
          
management:
  endpoint:
    health:
      show-details: always
    bus-refresh:
      enabled: true
        
  endpoints:
    web:
      exposure:
        include: "*"
          
gateway-url: http://202.149.218.74:10080
