server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,,application/xml,image/jpeg
    min-response-size: 2048
  http2:
    enabled: true
  servlet:
    context-path: /eatigoWeb
  port: 10081

spring:
  application:
    name: eatigoWeb
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  resources:
    cache:
      cachecontrol:
        cache-private: true
        cache-public: true
        max-age: 120
        must-revalidate: true
  servlet:
    multipart:
      file-size-threshold: 2KB
      location: /tmp
      max-file-size: 50MB
      max-request-size: 75MB
logging:
  level:
    root: INFO
    com.epps.eatigo.module.infrastructure.feignclient.EatigoCoreFeignClient: DEBUG
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://202.149.218.74:10089/eureka}
  instance:
    preferIpAddress: true

feign:
   client:
      config:
        default:
          connectTimeout: 900000
          readTimeout: 900000
          loggerLevel: FULL
          
gateway-url: http://202.149.218.74:10080
