spring:
   cloud:
      config:
         server:
            git:
               uri: https://github.com/abhineshkr/cloudconfig
   application:
      name: eatigoconfigserver
server:
   port: 10088


# Check - Multiple Zone Eureka Zone
#eureka:
  #client:
    #serviceUrl:
      #defaultZone: ${EUREKA_URI:http://localhost:10089/eureka}
  #instance:
    #preferIpAddress: true
    

management:
  endpoints:
    web:
      exposure:
        include: "*"
