
spring:
   application:
     name: eatigoBiiling
   zipkin:
     enabled: true
     base-url: http://202.149.218.74:9411
     sender:
      type: rabbit
   sleuth:
    sampler:
      probability: 1

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,,application/xml,image/jpeg
    min-response-size: 2048
  http2:
    enabled: true
  servlet:
    context-path: /eatigoBiiling
  port: 10085

management:
  endpoint:
    health:
      show-details: always
    bus-refresh:
      enabled: true
        
  endpoints:
    web:
      exposure:
        include: "*"
        
logging:
  level:
    root: INFO
    org.springframework.cloud.config: ERROR
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG

#Database Configuration
jdbc-url: jdbc:postgresql://202.149.218.74:5436/eatigo
jdbc-driverClassName: org.postgresql.Driver
jdbc-username: epps_programmer
jdbc-password: atul@1978eppsprogrammer

##maximum number of milliseconds that a client will wait for a connection
connection-timeout: 10000
##minimum number of idle connections maintained by HikariCP in a connection pool
minimum-idle: 10
##maximum pool size
maximum-pool-size: 30 
##maximum idle time for connection
idle-timeout: 10000
           
#defaullt value is 90 seconds
#lease-expiration-duration-in-seconds:60.

#default value is 60 seconds 
#lease-renewal-interval-in-seconds: 20  

#default eviction time : 60
# For Multiple Zone
  #z1: http://localhost:5001/eureka
  #z1: http://localhost:5001/eureka
  #z1: http://localhost:5001/eureka
eureka:
  instance:
     hostname: 202.149.218.74
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10089/eureka/

feign:
   compression:
      request:
        enable: true
        mime-types: text/xml,application/xml,application/json
        min-request-size: 2048
   client:
      config:
        default:
          connectTimeout: 60000
          readTimeout: 60000
          loggerLevel: FULL
        
gateway-url: http://202.149.218.74:10080
